INSERT IGNORE INTO movie (title, description, director, release_date, duration) VALUES
('Inception', 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.', 'Christopher Nolan', '2010-07-16', 148),
('The Dark Knight', 'When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological tests of his ability to fight injustice.', 'Christopher Nolan', '2008-07-18', 152),
('Interstellar', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity survival.', 'Christopher Nolan', '2014-11-07', 169),
('The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'Frank Darabont', '1994-09-23', 142),
('The Godfather', 'The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant son.', 'Francis Ford Coppola', '1972-03-24', 175),
('Pulp Fiction', 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.', 'Quentin Tarantino', '1994-10-14', 154),
('Schindlers List', 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.', 'Steven Spielberg', '1993-12-15', 195),
('The Lord of the Rings: The Fellowship of the Ring', 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring.', 'Peter Jackson', '2001-12-19', 178),
('Forrest Gump', 'The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man.', 'Robert Zemeckis', '1994-07-06', 142),
('Fight Club', 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.', 'David Fincher', '1999-10-15', 139),
('Goodfellas', 'The story of Henry Hill and his life in the mob, covering his marriage and his life of crime.', 'Martin Scorsese', '1990-09-19', 146),
('The Matrix', 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', 'Lana Wachowski', '1999-03-31', 136),
('Se7en', 'Two detectives hunt a serial killer who uses the seven deadly sins as his modus operandi.', 'David Fincher', '1995-09-22', 127),
('The Silence of the Lambs', 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to catch another serial killer.', 'Jonathan Demme', '1991-02-14', 118),
('Saving Private Ryan', 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.', 'Steven Spielberg', '1998-07-24', 169),
('Gladiator', 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.', 'Ridley Scott', '2000-05-05', 155),
('The Departed', 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.', 'Martin Scorsese', '2006-10-06', 151),
('Whiplash', 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing.', 'Damien Chazelle', '2014-10-10', 107),
('Parasite', 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', 'Bong Joon-ho', '2019-05-30', 132),
('The Grand Budapest Hotel', 'The adventures of Gustave H, a legendary concierge at a famous European hotel between the wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.', 'Wes Anderson', '2014-03-28', 99),
('No Country for Old Men', 'Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and takes the money while being pursued by a relentless killer.', 'Joel Coen', '2007-11-09', 122),
('There Will Be Blood', 'A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business.', 'Paul Thomas Anderson', '2007-12-26', 158),
('Mad Max: Fury Road', 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners.', 'George Miller', '2015-05-15', 120),
('La La Land', 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.', 'Damien Chazelle', '2016-12-09', 128),
('The Revenant', 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.', 'Alejandro G. Inarritu', '2015-12-25', 156);
